In [ ]:
from google.colab import files
uploaded = files.upload()
import pandas as pd

df = pd.read_excel("data_analysis_role_scraping.xlsx")
df = df.dropna(subset=["Job Title"])
df["Salary Type"] = df["Salary Type"].fillna("unspecified")
df["Salary Type"].value_counts()
df["Work Type"] = df["Work Type"].str.lower().str.strip()
df["Work Type"].value_counts()
df["Role Level"] = df["Role Level"].str.lower().str.strip()
df["Role Level"].value_counts()
skills_list = ["sql", "excel", "python", "tableau", "power bi"]
def extract_skills(text):
    text = str(text).lower()
    found = [skill for skill in skills_list if skill in text]
    return ", ".join(found) if found else "unspecified"
df["Skills"] = df["Description"].apply(extract_skills)
df["Skills"].value_counts()

df.info()
df.head(27)

Saving data_analysis_role_scraping.xlsx to data_analysis_role_scraping (9).xlsx
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Job Title       27 non-null     object
 1   Company         27 non-null     object
 2   Location        27 non-null     object
 3   Minimum Salary  22 non-null     float64
 4   Maximum Salary  22 non-null     float64
 5   Salary Type     27 non-null     object
 6   Description     27 non-null     object
 7   Source          26 non-null     object
 8   Work Type       27 non-null     object
 9   Skills          27 non-null     object
 10  Role Level      27 non-null     object
dtypes: float64(2), object(9)
memory usage: 2.4+ KB

,Job Title,Company,Location,Minimum Salary,Maximum Salary,Salary Type,Description,Source,Work Type,Skills,Role Level
0,Data Analyst Intern,Salute,"Seattle, WA",25.00,25.00,Hourly,Salute is a leading provider of cutting-edge D...,Indeed,unspecified,"sql, excel, python, tableau, power bi",intern
1,Insurance Operations Project Intern,ByteDance,"Seattle, WA",33.25,33.25,Hourly,The Global Payment team of ByteDance provides ...,LinkedIn,unspecified,"sql, excel",intern
2,Supply Chain Intern,Fluke Corporation,"Everett, WA",NaN,NaN,unspecified,About the job\nWe are seeking a motivated ‘sys...,LinkedIn,on-site,excel,intern
3,CI-Ops Information Analyst Intern,Premera Blue Cross,"Mountlake Terrace, WA",NaN,NaN,unspecified,About the job\nWorkforce Classification:\n\nHy...,LinkedIn,hybrid,unspecified,intern
4,Data Analytics Intern,MultiCare Health System,"Tacoma, WA",NaN,NaN,unspecified,"At MultiCare, we strive to offer a true sense ...",LinkedIn,remote,unspecified,intern
5,Business Insights & Analytics Intern,Seattle Seahawks,"Renton, WA",22.75,22.75,Hourly,Job Title: Business Insights & Analytics Inter...,LinkedIn,on-site,"sql, excel, python, tableau",intern
6,Data Analyst Intern,TikTok,"Seattle, WA",33.25,52.25,Hourly,The Global e-commerce Data Science team aims t...,LinkedIn,unspecified,"sql, tableau",intern
7,"Marketing Intern, Digital Analytics",SanMar,"Issaquah, WA",21.39,21.39,Hourly,"The Marketing Intern, Digital Analytics is res...",LinkedIn,hybrid,excel,intern
8,Application Portfolio Analyst Intern,Jacobs,"Seattle, WA",NaN,NaN,unspecified,"At Jacobs, we're challenging today to reinvent...",LinkedIn,hybrid,"excel, power bi",intern
9,Business Operations Analyst Intern,Pacific Seafood,"South Bend, WA",NaN,NaN,unspecified,"Pacific Seafood offers a unique, 13-week inter...",LinkedIn,on-site,excel,intern
10,"Data Analyst, RCX",Amazon,"Bellevue, WA",28.00,43.00,Hourly,We are looking for an experienced Data Analyst...,LinkedIn,on-site,"sql, excel",entry level
11,Business Data Analyst (Hybrid),eWaste.Pro,"University Place, WA",89000.00,150000.00,Salary,About the job\nCompany: eWaste.Pro Inc.\nLocat...,LinkedIn,hybrid,"sql, excel, tableau, power bi",entry level
12,"Systems Analyst, Supply Chain",SpaceX,"Woodinville, WA",85000.00,120000.00,Salary,SpaceX was founded under the belief that a fut...,LinkedIn,on-site,"sql, excel, python, tableau, power bi",entry level
13,Business Analyst,Amazon Web Services,"Seattle, WA",82000.00,97600.00,Salary,We are seeking a Business Analyst to support o...,LinkedIn,on-site,"sql, tableau, power bi",entry level
14,Area Revenue Analyst,Hyatt,"Seattle, WA",66100.00,95700.00,Salary,Join us for an incredible opportunity to becom...,LinkedIn,on-site,excel,entry level
15,Intern - Business Intelligence,SitusAMC,United States,22.50,25.00,Hourly,About the job\nSitusAMC is where the best and ...,LinkedIn,remote,"sql, excel",intern
16,Business Intelligence Analyst,Delta Dental of Washington,"Seattle, WA",70900.00,118100.00,Salary,We are looking for a dedicated Business Intell...,LinkedIn,on-site,"sql, excel, tableau",entry level
17,"Associate, Customer Experience- Data & Strategy",DoorDash,"Seattle, WA",64600.00,95000.00,Salary,"As an Associate, Customer Experience on the AC...",LinkedIn,on-site,"sql, python",mid level
18,"Associate Data Analyst, Customer Support",PitchBook,"Seattle, WA",75000.00,75000.00,Salary,"At PitchBook, a Morningstar company, we are al...",LinkedIn,on-site,"sql, excel",entry level
19,Data Analyst I,Stackline,"Seattle, WA",85000.00,105000.00,Salary,Stackline is the first full-funnel connected c...,LinkedIn,hybrid,"sql, python",mid level
20,Financial Analyst Intern,Terex Corporation,"Bothell, WA",26.00,26.00,Hourly,Early Talent Program Overview:\n\nThe Terex Ea...,LinkedIn,hybrid,"sql, excel, power bi",intern
21,Marketing Analytics and Measurement Internship,Wizards of the Coast,"Renton, WA",34.00,40.00,Hourly,"At Wizards of the Coast, we connect people aro...",LinkedIn,hybrid,"sql, tableau, power bi",intern
22,Data Analyst,Microsoft,"Redmond, WA",85100.00,169800.00,Salary,As a Data Analyst in the Analytics & Applicati...,LinkedIn,hybrid,"sql, power bi",mid level
23,Financial Analyst,Harbor Foods,"Lacey, WA",80900.00,90000.00,Salary,This position reports directly to the Director...,LinkedIn,on-site,"sql, excel",entry level
24,Data Analyst,Aditi Consulting,"Bellevue, WA",40.00,42.15,Hourly,Payrate: $40.00 - $42.15/hr.\n \nResponsibilit...,LinkedIn,remote,unspecified,entry level
25,Business Support Analyst,Delta Electronics Americas,"Bothell, WA",70000.00,85000.00,Salary,About the role:\n\nReview and reconcile report...,LinkedIn,on-site,excel,entry level
26,Junior Financial Analyst Supporting the USMS,FSA,"Seattle, WA",62580.00,70400.00,Salary,Be a part of the nationwide law enforcement in...,NaN,on-site,excel,entry level

In [ ]:
df["Role Level"].value_counts()

Role Level
intern         13
entry level    11
mid level       3
Name: count, dtype: int64

In [ ]:
from collections import Counter

all_skills = []

for skills in df["Skills"]:
    if skills != "unspecified":
        split_skills = skills.split(", ")
        all_skills.extend(split_skills)

skill_counts = Counter(all_skills)

skill_counts

In [ ]:
skill_df = pd.DataFrame(skill_counts.items(), columns=["Skill", "Count"])
skill_df = skill_df.sort_values(by="Count", ascending=False)

skill_df

      Skill  Count
1     excel     18
0       sql     17
3   tableau      8
4  power bi      8
2    python      5

In [ ]:
df["Skills"].value_counts()

Skills
excel                                    6
sql, excel                               5
unspecified                              3
sql, excel, python, tableau, power bi    2
sql, tableau, power bi                   2
sql, python                              2
sql, excel, python, tableau              1
excel, power bi                          1
sql, tableau                             1
sql, excel, tableau, power bi            1
sql, excel, tableau                      1
sql, excel, power bi                     1
sql, power bi                            1
Name: count, dtype: int64

In [ ]:
df["Work Type"].value_counts()

Work Type
on-site        13
hybrid          8
unspecified     3
remote          3
Name: count, dtype: int64

In [ ]:
df.to_excel("cleaned_job_data.xlsx", index=False)
skill_df.to_excel("skills_summary.xlsx", index=False)

In [ ]:
from google.colab import files

files.download("cleaned_job_data.xlsx")
files.download("skills_summary.xlsx")